name: findoutmole
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.8.0

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_auth_web: ^5.14.3
  cloud_firestore: ^5.6.8

  # Imagen y edición
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.6
  image_editor: ^1.6.0
  file_picker: ^10.1.9


  # Red y utilidades
  http: ^1.4.0
  http_parser: ^4.1.2
  path: ^1.9.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts: []
