name: findoutmole
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.15.3
  image_picker: ^1.0.7 # o la versión más reciente
  permission_handler: ^12.0.0+1 # o la versión más reciente
  image_editor: ^1.3.0  # o la versión más reciente
  cloud_firestore: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts: []
